// ANSWERS
// CLOSE this right now if you don't want to see answers.

const words = [
    "FRAME","GRAZE", "WINDY", "PAINT", "GOURD", "SWING", "VAPES", "AUDIO", 
    "FARTS","ADIEU",
    "SHEET","POUND","CAUSE","WORLD","SPORT","FINAL","CROSS","SENSE","WASTE",
    "DOUBT","SHAPE","FOCUS","WHILE","GRASS","AGENT","SCALE","FRUIT","NORTH",
    "HENRY","TOWER","COURT","FORCE","VIDEO","FRONT","SPACE","MONEY","PLACE",
    "VOICE","TREND","CHILD","LIGHT","UNCLE","STAND","COAST","PRESS","DEPTH",
    "CRIME","BUYER","BASIS","FAULT","WATER","COVER","GLASS","DANCE","WATCH",
    "LUNCH","TASTE","PARTY","THING","AWARD","DRINK","HOTEL","EVENT","LAURA",
    "STOCK","SMOKE","DRAFT","JAPAN","STYLE","TRACK","TRADE","PETER","UNITY",
    "MUSIC","EIGHT","SLICE","ABUSE","INPUT","TRUTH","APPLE","TITLE","CLASS",
    "ERROR","TERRY","RUGBY","STONE","MARCH","TOUCH","COACH","SHINE","SHARE",
    "PLANT","MAJOR","OWNER","CROWN","PAPER","SHEEP","WHOLE","BROWN","BLOOD",
    "POINT","RADIO","CHINA","MODEL","SHIFT","ENEMY","STATE","BREAD","SMILE",
    "SERVE","TRUST","PLATE","GREEN","PITCH","PHONE","RIGHT","CLOCK","SPEED",
    "STORE","PRIDE","CHIEF","JONES","STEAM","QUEEN","ELECT","THEME","PLANE",
    "MATCH","OUIJA","PHASE","FIELD","KNIFE","TRIAL","SOUTH","EBONY","EARTH",
    "STEEL","BREAK","BOARD","SKILL","ISSUE","PEACE","MOUTH","CREAM","RIVER",
    "NOISE","HEART","ORDER","IMAGE","SUGAR","RATIO","SCORE","EVERY","MONTH",
    "WHITE","PRICE","TABLE","BIRTH","ENTRY","LIMIT","LEVEL","JUDGE","PIECE",
    "MOTOR","PANEL","EAGER","SHOCK","FRAME","ROUND","EXTRA","SLEEP","HOUSE",
    "CHAIR","SOUND","ANGER","DREAM","CLAIM","RANGE","FRANK","OTHER","SCENE",
    "EDICT","LAYER","NOVEL","SHIRT","STUFF","METAL","DEATH","DRESS","REPLY",
    "GRANT","CHAIN","START","GROUP","PRIZE","ROUTE","PROOF","LEWIS","NIGHT",
    "SOLID","SMITH","SHARP","TRAIN","OFFER","WOMAN","FLOOR","STAGE","ADULT",
    "TOTAL","SIMON","VISIT","PILOT","FIGHT","INDEX","NURSE","SHELF","CHEST",
    "SIGHT","YOUTH","VALUE","ELITE","STUDY","FAITH","SQUAD","POWER","HORSE",
    "DRAMA","UNION","DRIVE","CROWD","STAFF","BRAIN","SPITE","SCOPE","BLOCK",
    "CYCLE","GUIDE","BEACH",
];


export default words;